swagger: "2.0"
info:
  description: "This is a sample server ETransfer server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger ETransfer"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "Natinality"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "FundDetails"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /natinality:
    post:
      tags:
      - "Natinality"
      summary: "Add a new Natinality"
      description: ""
      operationId: "addNatinality"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Natinality"
      responses:
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    put:
      tags:
      - "Natinality"
      summary: "Update an existing pet"
      description: ""
      operationId: "updateNatinality"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Natinality object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Natinality"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Natinality not found"
        405:
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /natinality/{id}:
    get:
      tags:
      - "Natinality"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getNatinalityById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Natinality"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Natinality not found"
    delete:
      tags:
      - "Natinality"
      summary: "Deletes a Natinality"
      description: ""
      operationId: "deleteNatinality"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "natinality id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "natinality not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /fundDetails:
    post:
      tags:
      - "FundDetails"
      summary: "Add a new FundDetails"
      description: ""
      operationId: "addFundDetails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/FundDetails"
      responses:
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    put:
      tags:
      - "FundDetails"
      summary: "Update an existing FundDetails"
      description: "update fund detail"
      operationId: "updateFundDetails"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "FundDetails object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/FundDetails"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "FundDetails not found"
        405:
          description: "Validation exception"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
        
  /fundDetails/{id}:
    get:
      tags:
      - "FundDetails"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getFundDetailsById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/FundDetails"
        400:
          description: "Invalid ID supplied"
        404:
          description: "FundDetails not found"
    delete:
      tags:
      - "FundDetails"
      summary: "Deletes a FundDetails"
      description: "delete fund details"
      operationId: "deleteFundDetails"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "FundDetails id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "FundDetails not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    # authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "password"
    tokenUrl: "http://petstore.swagger.io/oauth/dialog"
    scopes:
      write:pets: "modify natinality in your account"
      read:pets: "read your natinality"
definitions:
  Natinality:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      nationalityCode:
        type: "string"
      name:
        type: "string"
        example: "doggie"
      nationalityEn:
        type: "string"
        example: "USA"
      nationalityChi:
        type: "string"
        example: "美國"
      SortOrder:
        type: "integer"
        example: "1"
        
  FundDetails:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      fundDetailsEn:
        type: "string"
        example: "Manulife MPF 2020 Retirement Fund*"
      name:
        type: "string"
        example: "doggie"
      fundCodeEn:
        type: "string"
        example: "SHK139"
      fundTypeEn:
        type: "string"
        example: "Mixed Asset"
      fundDetailsCh:
        type: "string"
        example: "宏利MPF 2020退休基金*"
      fundCodeCh:
        type: "string"
        example: "SHK139"
      fundTypeCh: 
        type: "string"
        example: "混合資產基金"
      sortOrder: 
        type: "integer"
        example: "1"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"