server:
  servlet:
    context-path: /api/v1/
  port: 8081

springfox:
  documentaion:
    swagger:
      v2:
        path: /api-docs

#spring:
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles:
#        - ADMIN
e-transfer-security:
  app-client-id: eTransfer-mobile-client
  app-client-secret: ccUyb6vS4S8nxfbKPCrN