server:
  servlet:
    context-path: /api/v1/
  port: 8081

springfox:
  documentaion:
    swagger:
      v2:
        path: /api-docs

spring:
#  cache:
#    ehcache:
#      config: classpath:ehcache.xml
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-idle: 8 #连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间
        min-idle: 0 #连接池中的最小空闲连接

e-transfer-security:
  app-client-id: eTransfer-mobile-client
  app-client-secret: ccUyb6vS4S8nxfbKPCrN